### ISSUE TITLE
Tagged release?

### ISSUE THREAD

**Issue by sbrun** [kurobeats/fimap#82]
Hello,
It would be great to make a tagged release for the next releases.
In kali (and other distros I think) we have tools that monitors web pages listing release, and it works well with github pages showing git tags. If you make a tagged release we will be automatically informed and we will update the package quickly.
Thanks

**Comment by Oweoqi** [comment]
Hi Sophie,
While I'm happy to honour your request and simply maintain this repo as a mirror of the official, the creator of fimap forked my repo to his own instance after I ported it to github. It can be found here: https://tha-imax.de/git/root/fimap

**Comment by kurobeats** [comment]
Really late to action this, but I have now tagged release 1.0 and have started to port to python3.
